name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - master
      - development
  pull_request:
    branches:
      - main
      - master
      - development

permissions:
  contents: write  # Allow release creation & asset upload

jobs:
  build:
    name: Build & release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # use your version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create ZIP package
        run: |
          mkdir release
          cp build/app/outputs/flutter-apk/app-release.apk release/
          zip -r release-package.zip release

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | cut -d "+" -f1)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV  # Save version as an environment variable

      - name: Create and push tag
        run: |
          git tag ${{ env.VERSION }}  # Use the version from pubspec.yaml as the tag
          git push origin ${{ env.VERSION }}  # Push the tag to the repository

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}  # Use the extracted version as the tag
          name: Release ${{ env.VERSION }}
          body: |
            🎉 Automated release created for version: `${{ env.VERSION }}`.
            This release contains the built APK and ZIP package.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK and ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            release-package.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
